### ISSUE TITLE
Illegal argument exception

### ISSUE THREAD

**Issue by SlimeDog** [JyckoS/Blackhole#7]
Spigot 1.13.2
Blackhole 3.0.4

Default pulled_blocks section of config.yml
```
pull_blocks: true
unaffected_blocks:
- CHEST 
- FURNACE
- TRAPPED_CHEST
- DROPPER
- SHULKER_BOX
- ENDER_CHEST
```

Console/log error every tick
```
[09:48:07] [Server thread/WARN]: [Blackhole] Task #32 for Blackhole v3.0.3 generated an exception
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.EntityItem.setItemStack(EntityItem.java:375) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.EntityItem.<init>(EntityItem.java:40) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.dropItem(CraftWorld.java:313) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.dropItemNaturally(CraftWorld.java:329) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at com.gmail.jyckosianjaya.blackhole.manager.BHManager$2$3.run(BHManager.java:221) ~[?:?]
        at com.gmail.jyckosianjaya.blackhole.manager.BHManager$3.run(BHManager.java:265) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar-2019-04-08-0742:git-Spigot-f09662d-7c395d4]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Adding
```
- AIR
```
and rebooting the server does not resolve the issue.

**Comment by SlimeDog** [comment]
Adding
```
- AIR
```
seems to have resolved the issue.
